### ISSUE TITLE
opencv 3.3.0 - object has no attribute 'load' - TASS.py

### ISSUE THREAD

**Issue by svente08** [TechBubbleTechnologies/IoT-JumpWay-RPI-Examples#4]
Hi all,

something changed in version 3.3.0?

To begin I got this error running TASS but I guess I fixed it.

Traceback (most recent call last):
  File "TASS.py", line 78, in <module>
    model = cv2.face.createEigenFaceRecognizer(threshold=TASS.configs["ClassifierSettings"]["predictionThreshold"])
AttributeError: module 'cv2.face' has no attribute 'createEigenFaceRecognizer'

----> running: " .... cv2.face.EigenFaceRecognize_create ..."

With this issue your help would be very appreciated:

File "TASS.py", line 79, in <module>
    model.load(TASS.configs["ClassifierSettings"]["Model"])
AttributeError: 'cv2.face_EigenFaceRecognizer' object has no attribute 'load'

Thx

**Comment by AdamMiltonBarker** [comment]
Hi thanks for submitting an issue, I hope we can work things out for you. Nothing has changed on our side, if you follow the instructions provided for installing OpenCV, our example uses 3.1.0, I would suggest trying with that to see if it resolves your issue. 

Please follow the instructions below exactly and the versions of the software that are mentioned to you and let me know how you get on. 

https://github.com/TechBubbleTechnologies/IoT-JumpWay-RPI-Examples/tree/master/Computer-Vision/Python

**Comment by AdamMiltonBarker** [comment]
Closing due to inactivity.
